version: "3.7"
networks:
  spark-network:
    name: spark-network
services:
  zookeeper:
    image: yanleaon/zookeeper
    ports:
      - "2181:2181"
    networks:
      - spark-network
  spark-master:
    image: yanleaon/spark-master:latest
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
       - ./apps:/opt/spark-apps
       - ./data:/opt/spark-data
    environment:
      - "SPARK_LOCAL_IP=spark-master"
    networks:
      - spark-network
  spark-worker:
    image: yanleaon/spark-worker:latest
    ports:
      - "9091-9093:8081"
    depends_on:
      - spark-master
    links:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=512m
      - SPARK_EXECUTOR_MEMORY=512m
    volumes:
       - ./apps:/opt/spark-apps
       - ./data:/opt/spark-data
    networks:
      - spark-network
    hbase-master-local:
      image: yanleaon/hbase-master-local:2.1.0
      volumes:
        - ./data/hbase:/data
      ports:
        - 16000:16000
        - 16010:16010
      environment:
        - MASTER_HOSTNAME=hbase-master-local
        - ZOOKEEPER_QUORUM=zookeeper:2181
        - REGIONSERVERS=hbase-local-regionserver
      links:
        - zookeeper
      depends_on:
        - zookeeper
      networks:
        - spark-network
    hbase-regionserver-local:
      image: yanleaon/hbase-regionserver-local:2.1.0
      volumes:
        - ./data/hbase:/data
      ports:
        - 16020:16020
        - 16030:16030
      environment:
        - REGIONSERVER_HOSTNAME=hbase-regionserver-local
        - ZOOKEEPER_QUORUM=zookeeper:2181
      links:
        - zookeeper
      depends_on:
        - zookeeper
      networks:
        - spark-network